Update pull-request.yml

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -20,10 +20,10 @@ jobs:
       - name: Install SwiftLint
         run: brew install swiftlint
 
-      - name: Run SwiftLint for changed files
+      - name: Run SwiftLint for Changed Files
         run: |
-          git fetch origin ${{ github.base_ref }}
-          CHANGED_SWIFT_FILES=$(git diff --name-only ${{ github.sha }} $(git merge-base ${{ github.sha }} ${{ github.base_ref }}) | grep '\.swift$')
+          git fetch origin main:main || echo "Failed to fetch main branch"
+          CHANGED_SWIFT_FILES=$(git diff --name-only main...${{ github.sha }} | grep '\.swift$')
           if [ -z "$CHANGED_SWIFT_FILES" ]; then
             echo "No Swift files changed."
           else
